### ISSUE TITLE
Issue on Ubuntu 16.04 with new var "cli_dependencies_packages" undefined

### ISSUE THREAD

**Issue by davidcallen** [christiangda/ansible-role-awscli#5]
Using version 1.0.1

When using role on Ubuntu 16.04 I get this error : 
```
amazon-ebs: TASK [christiangda.awscli : Install "{{ cli_dependencies_packages }}" dependencies] ***
    amazon-ebs: fatal: [default]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'cli_dependencies_packages' is undefined\n\nThe error appears to be in '/home/david.allen/dev-cloud/host-main/cloud/packer/ibm-mq-official/ansible/roles/christiangda.awscli/tasks/install-ubuntu.yml': line 9, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Install \"{{ cli_dependencies_packages }}\" dependencies\n  ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes. Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}
```

I didnt see this error on version 1.0.0

I think the issue is caused by : 

In tasks/main.yml : 
```
- name: Include variables for Ubuntu
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}.yml"
    - "main.yml"
```

So above code it tries to include vars/ubuntu-16.yml but it doesn't exist and therefore includes file vars/main.yml

However vars/main.yml does not define the new var "cli_dependencies_packages".

My workaround/fix was to change main.yml to add below lines :  
```
+ cli_dependencies_packages:
+  - python-pip
```

Note: main.yml can be used by Redhat/Centos so may be safer to have a new vars/ubuntu.yml to hold this var (similar to the vars/debian.yml file).
